version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  # ==============
  # region Client Gateway
  # ==============
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./client-gateway/.env.dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  # =====================
  # region Products Microservice
  # =====================
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./products-ms/.env.dev
    # environment:
    #   - PORT=3001
    #   - DATABASE_URL=file:./dev.db
    #   - NATS_SERVERS=nats://nats-server:4222

  # =====================
  # region Orders Microservice
  # =====================
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./orders-ms/.env.dev
    # environment:
    #   - PORT=3002
    #   - DATABASE_URL=postgres://postgres:123456@orders-db:5432/ordersdb?schema=public
    #   - NATS_SERVERS=nats://nats-server:4222

  orders-db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

  # =====================
  # region Payments Microservice
  # =====================
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./payments-ms/.env.dev
    # environment:
    #   - PORT=${PAYMENTS_MS_PORT}
    #   - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    #   - PAYPAL_SECRET=${PAYPAL_SECRET}
    #   - PAYPAL_SUCCESS_URL=${PAYPAL_SUCCESS_URL}
    #   - PAYPAL_CANCEL_URL=${PAYPAL_CANCEL_URL}
    #   - PAYPAL_WEBHOOK_ID=${PAYPAL_WEBHOOK_ID}
    #   - PAYPAL_API_URL=${PAYPAL_API_URL}
    #   - PAYPAL_API_VERIFY_WEBHOOK_SIGNATURE=${PAYPAL_API_VERIFY_WEBHOOK_SIGNATURE}

  # =====================
  # region Auth Microservice
  # =====================
  auth-ms:
    # depends_on:
    #   - auth-db
    container_name: auth-ms
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./auth-ms/.env.dev

  # auth-db:
  #   image: mongo:7.0
  #   container_name: auth-db
  #   restart: always
  #   volumes:
  #     - ./auth-ms/mongo:/data/db
  #     - ./auth-ms/mongo/log:/var/log/mongodb/
  #     - ./auth-ms/mongo/mongo-keyfile:/data/mongo-keyfile
  #   ports:
  #     - 27017:27017
  #   command: ["--replSet", "rs0", "--keyFile", "/data/mongo-keyfile"]
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${AUTH_MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${AUTH_MONGO_INITDB_ROOT_PASSWORD}
